cbot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from chatterbot.ext.django_chatterbot import urls as chatterbot_urls
from example_app.views import ChatterBotAppView

app_name="chatterbot"


urlpatterns = [
    url(r'^chatterBot/$', ChatterBotAppView.as_view(), name='cbot_main'),
    #url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^api/chatterbot/', include(chatterbot_urls, namespace='chatterbot')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from forum import views
from django.conf.urls import include, url
from chatterbot.ext.django_chatterbot import urls as chatterbot_urls
from cbot.views import ChatterBotAppView

app_name="chatterbot"

urlpatterns = [
    url(r'admin/', admin.site.urls),
    #url(r'^time/$', views.current_datetime),
    #url(r'^time/(\d{1,2})/$', views.page_counter),
    url(r'^$', views.homepage),
    #url(r'^scripts/(?P<path>.*)$', serve, {'document_root': './scripts'}),
    url(r'^board/$', views.index),
    url(r'^board/writeSubject/$', views.writeSubject),
    url(r'^postSubject/$', views.postSubject),
    url(r'^(?P<subject_id>\d+)/$', views.readSubject),
    url(r'^(?P<subject_id>\d+)/add/$', views.addComment),
    url(r'^(?P<subject_id>\d+)/postComment/$', views.postComment),
    url(r'^chatterBot/$', ChatterBotAppView.as_view(), name='cbot_main'),
    url(r'^api/chatterbot/', include(chatterbot_urls, namespace='chatterbot')),
    url(r'^tourist2\.csv$', views.tourist),
    url(r'^data/$', views.data),

    #url(r'^api/chatterbot/', chatterbot_urls, namespace='chatterbot'),
    #url(r'^chatterbot/', include('chatterbot.ext.django_chatterbot.urls', namespace='chatterbot', app_name='chatterbot')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cbot/models.py
from django.db import models

# Create your models here.

forum/models.py
from django.db import models



class Subject(models.Model):
    title = models.CharField(max_length=128)
    name = models.CharField(max_length=64)
    date = models.DateTimeField('date')
    content = models.TextField()

class Comment(models.Model):
    reference = models.ForeignKey(Subject, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    date = models.DateTimeField('date')
    content = models.TextField()

cbot/views.py
from django.views.generic.base import TemplateView


class ChatterBotAppView(TemplateView):
    template_name = "templates/app.html"

forum/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from forum.models import Subject, Comment
from django.http import HttpResponseRedirect
from datetime import datetime


def homepage(request):
    return render(request, 'templates/homepage.html') 

def data(request):
    return render(request, 'templates/data.html') 

def tourist(request):
    return render(request, 'static/tourist2.csv')    

def index(request):
    subject_list = Subject.objects.all().order_by('date')[:]
    #return render_to_response('templates/board_index.html', {'subject_list': subject_list})
    return render(request, 'templates/board_index.html', {'subject_list': subject_list})

def writeSubject(request):
    #return render_to_response('templates/board_new.html') 
	return render(request, 'templates/board_new.html') 

def postSubject(request):
    s = Subject()
    s.title = request.POST['title']
    s.name = request.POST['name']
    s.content = request.POST['content']
    s.date = datetime.now()
    s.save()
    return HttpResponseRedirect('/%s/' % s.id)      

def readSubject(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'templates/board_read.html', {'subject': subject, 'comments':subject.comment_set.all()})

def addComment(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'templates/board_reply.html', {'subject': subject}) 
    
def postComment(request, subject_id):
    s = get_object_or_404(Subject, pk=subject_id)
    c = s.comment_set.create(name=request.POST['name'], content=request.POST['content'], date=datetime.now())
    c.save()
    return HttpResponseRedirect('/%s/' % s.id) 

         

templates/app.html
<!--{% load staticfiles %}-->
<!doctype html>
<html>
    <head>
        <title>Online service</title>
        <link rel="stylesheet" href="../static/css/bootstrap.css" type="text/css">
        <link rel="stylesheet" href="../static/css/custom.css" type="text/css">
    </head>
    <body>
        <div class="container">
            <div class="jumbotron mt-1">
                <h1 class="heading">Online Service</h1>
                <div class="content">
                    <a class="sidebar" href="/">Back to Homepage</a>

                    <hr class="my-2">

                    <div class="row">
                        <div class="col-xs-6 offset-xs-3">
                            <div class="list-group chat-log js-chat-log"></div>
                                <div class="input_group input-group-lg mt-1">
                                   <input type="text" class="form-control js-text input_text" placeholder="Type your question here"/>
                                    <span class="input-group-btn">
                                    <button class="btn btn-primary js-say btn_submit">Submit</button>
                                    </span>
                                </div>
                        </div>
                    </div>
                </div>    
            </div>
        </div>

        <script src="../static/js/jquery.js"></script>
        <script src="../static/js/js.cookie.js"></script>
        <script src="../static/js/bootstrap.js"></script>
        <script>
            var chatterbotUrl = '{% url "chatterbot:chatterbot" %}';
            var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            var $chatlog = $('.js-chat-log');
            var $input = $('.js-text');
            var $sayButton = $('.js-say');
            createRow("Hi, welcome to Melbourne! How can I help you?");

            function createRow(text) {
                //var $row = $('<li class="list-group-item"></li>');
                var $row = $('<div class="list-group-item"></div>');
                $row.text(text);
                $chatlog.append($row);
            }
            function submitInput() {
                var inputData = {
                  'text': $input.val()
                }
                // Display the user's input on the web page
                createRow(inputData.text);
                var $submit = $.ajax({
                    type: 'POST',
                    url: chatterbotUrl,
                    data: JSON.stringify(inputData),
                    contentType: 'application/json'
                });
                $submit.done(function(statement) {
                    createRow(statement.text);
                    // Clear the input field
                    $input.val('');
                    // Scroll to the bottom of the chat interface
                    $chatlog[0].scrollTop = $chatlog[0].scrollHeight;
                });
                $submit.fail(function() {
                  // TODO: Handle errors
                });
            }
            $sayButton.click(function() {
                submitInput();
            });
            $input.keydown(function(event) {
                // Submit the input when the enter button is pressed
                if (event.keyCode == 13) {
                    submitInput();
                }
            });
        </script>
    </body>
</html>

templates/base.html
<!DOCTYPE html>

<html>
 
	<head>
		<title>{% block title %} Discussion board {% endblock %}</title>
		<link rel=stylesheet href="/static/css/style_discussion board.css" type="text/css">
	</head>
 
	<body>
		<div class="wrapper">
			<div class="heading"><center><h1>{% block title2 %}{% endblock %}<h1></center></div>
 
			<div class="content">
				<div id="sidebar" class="sidebar">{% block sidebar %}{% endblock %}</div>
				<div class="sidebar">{% block sidebar2 %}{% endblock %}</div><br>
				<div class="topic" id="entries">{% block content %}{% endblock %}</div>

			</div>
		</div>
	</body>
 
</html>

templates/board_index.html
{% extends "templates/base.html" %}
 
{% block title %}
Discussion board - Homepage
{% endblock %}

{% block title2 %}
Discussion board - Homepage
{% endblock %}
 
{% block content %}
	{% if subject_list %}
		<ul>
		{% for subject in subject_list %}
			<li> 
				<div class="instance">
					<p>{{ subject.date|date:"f j F Y" }}    Author：<b>{{ subject.name}}</b><br>
					<a href="/{{subject.id}}/">{{ subject.title }}</a></p>
				</div>
			</li>
		{% endfor %}
		</ul>
	{% else %}
	No any topic available for now...
 
	{% endif %}
{% endblock %}
 
{% block sidebar %}
	<a href="writeSubject">Add new topic</a>
{% endblock %}

{% block sidebar2 %}
	<a href="/">Back to Homepage</a>
{% endblock %}

templates/board_new.html
{% extends "templates/base.html" %}
 
{% block title %}
Discussion board - new topic
{% endblock %}

{% block title2 %}
Discussion board - new topic
{% endblock %}
 
{% block content %}
	<form action="/postSubject/" method="post">
		Topic:<br>
		<input type="text" name="title"><br> 
		Author:<br>
		<input type="text" name="name"><br> 
		Content:<br>
		<textarea rows="10" cols="70" name="content"></textarea>
		<p/>
		<input type="submit" value="Post">
		{% csrf_token %}
	</form>
{% endblock %}
 
{% block sidebar %}
<a href="/board">Back to Discussion board</a>
{% endblock %}

{% block sidebar2 %}
<a href="/">Back to Homepage</a>
{% endblock %}

templates/board_read.html
{% extends "templates/base.html" %}
 
{% block title %}
Discussion board - {{ subject.title }}
{% endblock %}

{% block title2 %}
Discussion board - {{ subject.title }}
{% endblock %}

 
{% block content %}
	<h1>Topic：{{ subject.title }}</h1>
  	<b>Author: </b>{{ subject.name}}<br>
  	<b>Time: </b>{{ subject.date|date:"j F, Y" }}<br>
	<p><div class="text_read">{{subject.content}}</div></p>
 
	{% if comments %}
		<p class="comment_break">--- Comments on the topic ---</p>
		{% for comment in comments %}
			<div class="reply"> 
				{{ comment.date|date:"j F, Y" }} replied by -- <b>Author: </b>{{ comment.name}}
 				<p class="comment_content">{{ comment.content }}</p>
 			</div>	
		{% endfor %}
	{% else %}
		<p class="reply">No reply for now</p>
	{% endif %}
{% endblock %}
 
{% block sidebar %}
	<a href="add">Reply the topic</a>
{% endblock %}

{% block sidebar2 %}
	<a href="/board">Back to Discussion Board</a><br>
{% endblock %}

templates/board_reply.html
{% extends "templates/base.html" %}
 
{% block title %}
	Discussion board - Reply to the topic
{% endblock %}

{% block title2 %}
	Discussion board - Reply to the topic
{% endblock %}
 
{% block content %}
	<form action="/{{ subject.id }}/postComment/" method="post">
		<h1>Reply to: {{ subject.title }}</h1>
		Your name：<br>
		<input type="text" name="name"><br>
 		Your content:<br>
 		<textarea rows="10" cols="70" name="content"></textarea><br>
		<input type="submit" value="post" />
		{% csrf_token %}
	</form>
{% endblock %}
 
{% block sidebar %}
	<a href="/board">Back to Discussion board</a>

{% endblock %}

{% block sidebar2 %}
	<a href="/">Back to Homepage</a>
{% endblock %}

templates/data.html
<!DOCTYPE html>

<html lang="en">
	<head prefix="og: http://ogp.me/ns#">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Data</title>
		<!-- Libraries -->
		<script type="text/javascript" src="//codeorigin.jquery.com/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="//d3js.org/d3.v3.min.js"></script>
		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.3/angular.min.js"></script>
		<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
		<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js">
		</script>
		<!-- Customed files -->
		<link rel="stylesheet" type="text/css" href="../static/css/data.css">
		<script type="text/javascript" src="../static/js/data.js"></script>
	</head>

	<body>
		<div id="root">
			<div><center>This is a test</center></div>

			<div id="svg">
				<svg width="100%" height="600px" viewBox="0 0 800 600" preserveAspectRatio="xMidYMid"></svg>
			</div>	
		</div>

	</body>
</html

templates/nav.html
{% load staticfiles %}

<nav class="navbar navbar-dark bg-inverse navbar-full">

  <a class="navbar-brand" href="{% url 'cbot_main' %}">
    <img src="{% static 'img/chatterbot.png' %}" width="30" height="30" class="d-inline-block align-top" alt="ChatterBot">
    ChatterBot
  </a>

  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="http://chatterbot.readthedocs.io/en/stable/">Documentation</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="https://github.com/gunthercox/ChatterBot">GitHub</a>
    </li>
  </ul>

  <ul class="nav navbar-nav float-xs-right">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'chatterbot:chatterbot' %}">API</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
    </li>
  </ul>
</nav>

templates/now.html
<html>
	<head>
		<title>顯示現在時間</title>
	</head>
 
	<body>
		<h1>現在時間是 {{ current_time }} 。</h1>
 
			你好啊！
			右邊會隨機出現一個0到9之間的整數： {{ number|random }}
	</body>
</html>

templates/page.html
<html>
	<head>
		<title>顯示頁數及現在時間</title>
	</head>
 
	<body>
		<h1>現在時間是 {{ current_time }} 。</h1>
		{% ifequal offset "99" %}
			<p>這是最後一頁囉！</p>
		{% else %}
			<p>您來到了第 {{ offset }} 頁。</p>
		{% endifequal %}
	</body>
</html>